INITIAL_LEADS = [
    {
        "id": 1,
        "full_name": "Аааа",
        "phone": "+998 7777777",
        "telegram_username": "@7777777",
        "region": "Сурхандарьинская область",
        "school": "инха",
        "question_text": "?",
        "status": "Bekor qildi",
        "is_contacted": False,
        "contacted_by": "@angelina_usm",
        "contacted_at": "2026-10-05 06:09:00",
        "created_at": "2026-10-05 06:08:44",
        "user_agent": "Telegram Bot (RU)"
    },
    {
        "id": 2,
        "full_name": "test",
        "phone": "+998 111111111",
        "telegram_username": "@test",
        "region": "Toshkent shahri",
        "school": "11",
        "question_text": None,
        "status": "Yangi",
        "is_contacted": False,
        "contacted_by": None,
        "contacted_at": None,
        "created_at": "2026-10-05 08:57:27",
        "user_agent": "Telegram Bot (UZ)"
    },
    {
        "id": 3,
        "full_name": "Jaloliddinov Salohiddin Ziyodulla o'g'li",
        "phone": "+998 997110938",
        "telegram_username": "@jaloliddinovff",
        "region": "Toshkent shahri",
        "school": "300-DIUM ni bitirgan",
        "question_text": None,
        "status": "Yangi",
        "is_contacted": False,
        "contacted_by": None,
        "contacted_at": None,
        "created_at": "2026-10-06 15:31:07",
        "user_agent": "Telegram Bot (UZ)"
    },
    {
        "id": 4,
        "full_name": "Mamatkulov Aziz Ilhomovich",
        "phone": "+998 508725842",
        "telegram_username": "@Azizjon_7o7",
        "region": "Samarqand viloyati",
        "school": "13-Maktab",
        "question_text": None,
        "status": "Yangi",
        "is_contacted": False,
        "contacted_by": None,
        "contacted_at": None,
        "created_at": "2026-10-06 15:45:53",
        "user_agent": "Telegram Bot (UZ)"
    },
    {
        "id": 5,
        "full_name": "Mardonova Mahliyo Davronovna",
        "phone": "+998 932118177",
        "telegram_username": "@Kaktus_br",
        "region": "Surxondaryo viloyati",
        "school": "23-umumiy o'rta ta'lim maktabi",
        "question_text": None,
        "status": "Yangi",
        "is_contacted": False,
        "contacted_by": None,
        "contacted_at": None,
        "created_at": "2026-10-06 16:18:51",
        "user_agent": "Telegram Bot (UZ)"
    },
    {
        "id": 6,
        "full_name": "Жиянов Шохрух Максудович",
        "phone": "+998 903224538",
        "telegram_username": "@Shoxch1k_1",
        "region": "г. Ташкент",
        "school": "280",
        "question_text": None,
        "status": "Yangi",
        "is_contacted": False,
        "contacted_by": None,
        "contacted_at": None,
        "created_at": "2026-10-06 18:06:44",
        "user_agent": "Telegram Bot (UZ)"
    },
    {
        "id": 7,
        "full_name": "Жиянов Шохрух Максудович",
        "phone": "+998 903224535",
        "telegram_username": "@Shxoch1k_1",
        "region": "г. Ташкент",
        "school": "280",
        "question_text": None,
        "status": "Yangi",
        "is_contacted": False,
        "contacted_by": None,
        "contacted_at": None,
        "created_at": "2026-10-06 18:07:56",
        "user_agent": "Telegram Bot (UZ)"
    },
    {
        "id": 8,
        "full_name": "Jabborov Abbos Axtamovich",
        "phone": "+998 873006022",
        "telegram_username": "@Abbos",
        "region": "Qashqadaryo viloyati",
        "school": "6 maktab",
        "question_text": None,
        "status": "Yangi",
        "is_contacted": False,
        "contacted_by": None,
        "contacted_at": None,
        "created_at": "2026-10-06 21:34:22",
        "user_agent": "Telegram Bot (UZ)"
    },
    {
        "id": 9,
        "full_name": "Muhammadsafo Xasanjonov",
        "phone": "+998 979591619",
        "telegram_username": "@khasanjonov_m",
        "region": "Toshkent shahri",
        "school": "Shaykhontohur TIM",
        "question_text": None,
        "status": "Yangi",
        "is_contacted": False,
        "contacted_by": None,
        "contacted_at": None,
        "created_at": "2026-10-07 02:12:22",
        "user_agent": "Telegram Bot (UZ)"
    },
    {
        "id": 10,
        "full_name": "Шадаминов Ратмир Ренатович",
        "phone": "+998 998889044",
        "telegram_username": "@RatmirShadaminov",
        "region": "г. Ташкент",
        "school": "260 школа",
        "question_text": "Включены ли участия в олимпиадах в курсы математики и физики? На каком языке будет проходить обучение? какое время будут проходить занятия по всем предметам и в какие дни.",
        "status": "Yangi",
        "is_contacted": False,
        "contacted_by": None,
        "contacted_at": None,
        "created_at": "2026-10-07 06:05:30",
        "user_agent": "Telegram Bot (UZ)"
    },
    {
        "id": 11,
        "full_name": "Иброхимов Мухаммадхабиб Еркинбек уг’ли",
        "phone": "+998 958281011",
        "telegram_username": "@Aston_McMissile",
        "region": "г. Ташкент",
        "school": "17-ая школа",
        "question_text": "Здравствуйте ТТ.\nЕсли у вас есть время на ответ , то можно ли задать вопрос ?\nЯ недавно закончил НТ «программирование» и хотелось спросить мы будем ли изучать программирование, так как это базовая часть инженера.\nЗаранее благодарю!",
        "status": "Yangi",
        "is_contacted": False,
        "contacted_by": None,
        "contacted_at": None,
        "created_at": "2026-10-07 07:15:49",
        "user_agent": "Telegram Bot (UZ)"
    }
]
